import { Button } from "@chakra-ui/react";
import { UserButton, useUser } from "@clerk/nextjs";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";

export default function Home() {
  const { user, isLoading } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (user) {
      router.push("/dashboard");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Produhacks | Doctor CRM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-12 h-screen flex justify-center items-center w-full ">
        <div className="flex items-center-justify-center text-center flex-col w-full md:w-1/2 space-y-4">
          <UserButton />
          <h1 className="text-4xl font-bold">Medlink</h1>
          <p>Manage your patient relations via a convenient CRM.</p>
          <div className="flex space-x-3 items-center justify-center">
            <a href="/sign-up">
              <Button colorScheme="blue">Sign Up</Button>
            </a>
            <a href="/sign-in">
              <Button colorScheme="blue">Log in</Button>
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
